# Generated by Django 5.1.7 on 2025-03-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customer_password_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='VAT_Number',
            field=models.CharField(default='', editable=False, max_length=9, unique=True),
            preserve_default=False,
        ),
    ]
