# Generated by Django 5.1.7 on 2025-03-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customer_vat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='VAT_Number',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
    ]
