# Generated by Django 5.1.7 on 2025-03-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='my_order',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='my_order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='my_order',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='my_order',
        ),
    ]
