# Generated by Django 5.1.7 on 2025-03-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
