# Generated by Django 5.1.7 on 2025-03-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_key_id',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_value_id',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
